# encoding: utf-8

# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{commentary}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Andras Tarsoly"]
  s.date = %q{2011-07-30}
  s.description = %q{A simple gem for managing comments on ActiveRecord models.}
  s.email = %q{tarsolya@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/commentary.rb",
    "test/helper.rb",
    "test/test_commentary.rb"
  ]
  s.homepage = %q{http://github.com/tarsolya/commentary}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Comments on ActiveRecord models.}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_runtime_dependency(%q<minitest>, [">= 0"])
      s.add_runtime_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_runtime_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["= 3.1.0.rc5"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0.2.4"])
      s.add_runtime_dependency(%q<mini_specunit>, [">= 0"])
      s.add_runtime_dependency(%q<mini_backtrace>, [">= 0"])
      s.add_runtime_dependency(%q<mini_shoulda>, [">= 0"])
    else
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<minitest>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rails>, ["= 3.1.0.rc5"])
      s.add_dependency(%q<mysql2>, [">= 0.2.4"])
      s.add_dependency(%q<mini_specunit>, [">= 0"])
      s.add_dependency(%q<mini_backtrace>, [">= 0"])
      s.add_dependency(%q<mini_shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<minitest>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rails>, ["= 3.1.0.rc5"])
    s.add_dependency(%q<mysql2>, [">= 0.2.4"])
    s.add_dependency(%q<mini_specunit>, [">= 0"])
    s.add_dependency(%q<mini_backtrace>, [">= 0"])
    s.add_dependency(%q<mini_shoulda>, [">= 0"])
  end
end

